# Webots Makefile for the Crazyflie controller

# List all the C files that need to be compiled
C_SOURCES = autonomus.c pid_controller.c

# This line links to the global file you just showed me
include $(WEBOTS_HOME)/resources/Makefile.include
